# Generated by Django 4.1.4 on 2024-01-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0017_fin_banking_fin_banktransactions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_banking',
            name='bank_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
