# Generated by Django 4.1.4 on 2024-01-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0018_fin_banking_bank_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_banktransactions',
            name='current_balance',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
